wandb_version: 1

task_lm:
  desc: null
  value: roberta-large
is_mask_lm:
  desc: null
  value: null
compute_zscore:
  desc: null
  value: true
incorrect_coeff:
  desc: null
  value: 180.0
correct_coeff:
  desc: null
  value: 200.0
dataset:
  desc: null
  value: sst-2
dataset_seed:
  desc: null
  value: 0
base_path:
  desc: null
  value: ./data
num_shots:
  desc: null
  value: 16
policy_lm:
  desc: null
  value: distilgpt2
hidden_size:
  desc: null
  value: 2048
logit_bias:
  desc: null
  value: 0.0
fluent:
  desc: null
  value: false
fluent_top_k:
  desc: null
  value: 20
max_decoding_length:
  desc: null
  value: 5
eos_token_id:
  desc: null
  value: null
prompt_length:
  desc: null
  value: 2
prompt_train_batch_size:
  desc: null
  value: 16
prompt_infer_batch_size:
  desc: null
  value: 1
source_str:
  desc: null
  value: <|endoftext|>
sql_loss_impl:
  desc: null
  value: v2_v2r_v3_v3r
training_mode:
  desc: null
  value: sql-onpolicy
mix_strategy:
  desc: null
  value: null
target_update_method:
  desc: null
  value: polyak
target_update_steps:
  desc: null
  value: null
target_learning_rate:
  desc: null
  value: 0.001
reward_shaping:
  desc: null
  value: true
reward_shaping_old_min:
  desc: null
  value: 0.0
reward_shaping_old_max:
  desc: null
  value: 1.0
reward_shaping_new_min:
  desc: null
  value: 0.0
reward_shaping_new_max:
  desc: null
  value: 5.0
top_k:
  desc: null
  value: 256
top_p:
  desc: null
  value: 1.0
num_beams:
  desc: null
  value: 1
train_batch_size:
  desc: null
  value: 32
train_shuffle:
  desc: null
  value: false
train_drop_last:
  desc: null
  value: true
num_train_epochs:
  desc: null
  value: 1
max_train_steps:
  desc: null
  value: 12000
do_eval:
  desc: null
  value: true
eval_batch_size:
  desc: null
  value: 32
eval_steps:
  desc: null
  value: 10
df_steps:
  desc: null
  value: 200
do_save:
  desc: null
  value: true
save_dir:
  desc: null
  value: outputs/2023-07-12/20-51-18/./outputs
save_steps:
  desc: null
  value: 100000
learning_rate:
  desc: null
  value: 5.0e-05
gradient_clip:
  desc: null
  value: true
gradient_clip_norm:
  desc: null
  value: 5.0
checkpoint_path:
  desc: null
  value: null
random_seed:
  desc: null
  value: null
report_to_wandb:
  desc: null
  value: true
project_name:
  desc: null
  value: rl-prompt
run_name:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.5
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1689209687.349542
    t:
      1:
      - 1
      - 11
      - 49
      - 50
      - 55
      2:
      - 1
      - 11
      - 49
      - 50
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.10.11
      5: 0.15.5
      6: 4.30.2
      8:
      - 5
